### ISSUE TITLE
UPM Support

### ISSUE THREAD

**Issue by mwnDK1402** [HolyShovelSoft/log4uni#3]
Would be convenient to package this repository as a UPM package. Are there any obstacles to doing this?

**Comment by mfandreich** [comment]
Hi!
Its in my plan, but I was doing it after fix silent crashes of editor. Main problem its that I dont have enough time right now...

**Comment by mwnDK1402** [comment]
I wanted to ask what obstacles there were because I'd like to do it, but I'm not familiar with the codebase.

**Comment by mfandreich** [comment]
In my opinion, the publication of software as a package should occur when the author is fully confident in its performance. At the moment, I'm not completely sure about this, as there is a critical bug that I have not been able to fix so far. As soon as I find it and fix it, I will immediately publish this wrapper as a package.

**Comment by mwnDK1402** [comment]
Mwahaha, package time. 👍

**Comment by mwnDK1402** [comment]
Unrelated to this issue, but how do you set up your development environment for working on this repository? Do you just clone it into a Unity assets folder? I'll do the same so I can contribute to the repository.

**Comment by mfandreich** [comment]
What repository you want to use? 
Right now this git repo dont ready for packaging, because it use link.xml files for prevent stripping. And this repo cant be simple imported to unity project, because I need additional custom steps after build. Thats why for installing of this tool you need get release zip or unitypackage instead of source code. Or get this project and build it by self for using.
Anyway. Next step what I need to solve - its link.xml file. I need embed it in result dll. After it I setup CI on this repo for auto build and publish in npm.org (or maybe in OpenUPM if I found way do this from github actions).

**Comment by mwnDK1402** [comment]
> What repository you want to use?

This repository. I wasn't asking about the installation, I was asking what I need to do to be able to start contributing to it.

> Do you just clone it into a Unity assets folder? I'll do the same so I can contribute to the repository.

I'm very curious about how the project works, but I don't want to take too much of your time.

**Comment by mfandreich** [comment]
I think its out of theme of UPM. =)
If you want contribute to this repo or change it for your purposes - you can fork it, pull it and open solution with some .net IDE (rider or visual studio for example). Build solution. After it in your project was created folder "Build\Release" or "Build\Debug". Content of this folder can be imported in unity project. And this folder I publish as realeses in release section.
UPD. And if you want you can create PR for this repo. =)

**Comment by mfandreich** [comment]
About UPM. This repository will be published in the near future, but I cannot yet say for sure in which UPM.

**Comment by mwnDK1402** [comment]
UPM means Unity Package Manager. Is there more than one Unity Package Manager?

**Comment by mfandreich** [comment]
For using this in package manager you need git repo configured as package or package published on some public npm repository. All this stuff right now in process.

**Comment by mfandreich** [comment]
Ok. Right now its can be setup with UPM via git, I add links into readme. Issue still open because package not published in public repository yet.

**Comment by mwnDK1402** [comment]
> Ok. Right now its can be setup with UPM via git, I add links into readme. Issue still open because package not published in public repository yet.

I just tried it out, and it doesn't work yet, because there's no assembly definition in the package.

**Comment by mfandreich** [comment]
Its havent asmdef files because package itself (builded and ready for use) dont have any *.cs files, its contain pure .net dll files.

**Comment by mwnDK1402** [comment]
> Its havent asmdef files because package itself (builded and ready for use) dont have any *.cs files, its contain pure .net dll files.

Alright, how can you access the package, then? It's not accessible from projects using .asmdef files.

**Comment by mfandreich** [comment]
Its referenced to your code automaticly, as plain dlls in unity do it all time. You dont need reference it in asmdef except situations when you use "Override references" option in your asmdef.

**Comment by mwnDK1402** [comment]
When I install the package, there's no `.dll` files in it, for some reason.

**Comment by mwnDK1402** [comment]
I'll try installing it in an empty project.

**Comment by mfandreich** [comment]
Dll and sources of packages not imported to project itself. Downloaded packages placed to <ToyrProjectFolder>\Library\PackageCache\<package_id>@<package_ver> (id for this package its com.holyshovelsoft.opensource.log4uni). But its still can be used inside unity project. Thats like UPM work.
You can check that package installed and worked correctly with this point in menu:
![image](https://user-images.githubusercontent.com/11754076/116715197-ad59d680-aa00-11eb-84cb-ddd1713e50e1.png)
If its exitsts and works - thats mean that log4uni installed and worked fine.

**Comment by mwnDK1402** [comment]
I just installed it in an empty project, and it works in that one. The `.dll` files just weren't added to `Library\PackageCache\com.holyshovelsoft.opensource.log4uni@32ca7c36b3` in my existing project.

**Comment by mwnDK1402** [comment]
Actually, the files are there, they just don't show up in Unity.

**Comment by mfandreich** [comment]
Can you check menu item from my screenshot?

**Comment by mwnDK1402** [comment]
> Can you check menu item from my screenshot?

Works after a simple restart. :P

**Comment by mfandreich** [comment]
Glad to hear it! =)

**Comment by mfandreich** [comment]
Package added to OpenUPM https://openupm.com/packages/com.holyshovelsoft.opensource.log4uni/
